### ISSUE TITLE
Plugin seems to disable entire preview window, rather than just the PDF preview generation behavior

### ISSUE THREAD

**Issue by dfgshdsfh** [JJ-8/joplin-disable-pdf#1]
I recently updated joplin to the latest appimage from an ancient 1.*.* series version. I was disheartened to find the PDF preview change made things unusable, so I tried your plugin (version 1.0.0).

Unfortunately when your plugin is enabled, the entire preview window seems to be disabled containing nothing but "PDF is disabled". Is that what you intended?

Joplin Version info
Joplin 2.1.8 (prod, linux)

Client ID: 52d8beccca634fec93db37079ca57719
Sync Version: 2
Profile Version: 39
Keychain Supported: No

Revision: 94ea177

**Comment by JJ-8** [comment]
Thank you for including such detailed debug information!

Just the string "PDF is disabled" is the intended behavior of the plugin. The plugin overwrites the MarkdownIt render function to prevent the preview (and as a side effect also the export). I use the plugin when I only want to use the markdown editor for big notes without using the PDF preview.
My time is very limited but one day it would be awesome to have a "Push to PDF" button to trigger the rendering manually. But I don't have any plugin experience for Joplin and therefore it is a lot of work. So I can't implement it in the short term.
Did you expect a different behavior?

**Comment by dfgshdsfh** [comment]
Ah bummer. Thanks for the quick response.

>Did you expect a different behavior?

From reading the plugin description, I was under the impression that it would disable only the pdf previews so it would be just like how my old 1.4.19 version worked before, not disable the entire preview window. I would recommend noting explicitly saying the preview windows is disabled as well.

I'm also not a coder, but my next step was wondering if I could just break the pdf renderer somehow myself. If I can find something that works, I'll get back to you, but don't hold your breath. I do appreciate your effort so far though!

For reference I've also added my complaint here: https://discourse.joplinapp.org/t/disable-attachments-pdf-inline-preview/13706/7 but I don't really have hope that anything will change, ~~since in the first place they saw nothing wrong with forcing the feature without a way to turn it off.~~

*Edit* I spoke too soon, looks like there is a way to turn if off after all. The thread had me believe there was no way and I had missed it in the options the first time around. This is fit for my purpose, as I don't need or want the feature at all.
The setting can be found @ Tools->Options->Markdown->Enable PDF viewer (uncheck)

With that I suppose this issue can be closed.

**Comment by JJ-8** [comment]
Wait, so you can disable the preview completely?? I didn't know that :)
Well, that's a good reason to make this plugin more useful by adding the "Push to PDF" feature in the shorter term.

**Comment by JJ-8** [comment]
Ah, I just tested it and now I understand your confusion. The plugin was intended to completely disable the PDF view since it causes lots of performance issues on my end when typing in very large notes. But you were talking about inline PDF files in your notes which were also rendered in the PDF preview.
So the plugin can still be useful to disable the PDF completely :)
